/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>

#define ADC_BASE_ADDRESS 			0x50000000UL
#define ADC_CR1_REG_OFFSET  		0x08
#define ADC_CR1_REG_ADDR      		(ADC_BASE_ADDRESS + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDRESS			0x40021000UL
#define RCC_AHB_OFFSET 				0x14
#define AHB_ENR_ADDRESS				(RCC_BASE_ADDRESS+RCC_AHB_OFFSET)

int main(void)
{
	/* Modify the  ADC cr1 register*/
	uint32_t *pRccAhbReg = (uint32_t*) AHB_ENR_ADDRESS;

	uint32_t *pAdcCr1Reg =(uint32_t*) ADC_CR1_REG_ADDR;
	/* Modify the  ADC cr1 register*/
	*pRccAhbReg |= (1<< 28);
	/* Modify the  ADC cr1 register*/
	*pAdcCr1Reg |= (1 << 0);

	for(;;);
}
